/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package minesweeper;

public class App {
    public static void main(String[] args) {
        Grid test = new Grid("beginner");
        System.out.println("Answer Grid:");
        test.printGrid(test.getAnswerGrid());
        System.out.print("\n");
        System.out.println("User Grid:");
        test.printGrid(test.getUserGrid());
    }
}
