/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package minesweeper;

import static minesweeper.Game.newGame;

public class App {
    public static void main(String[] args) {
        newGame();
    }
}
