/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package minesweeper;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner scnr = new Scanner(System.in);
        System.out.println("Type beginner, intermediate, or expert to select difficulty:");
        String difficulty = scnr.nextLine();
        scnr.close();
    }
}
